name = "MethodOfFundamentalSolutions"
uuid = "ba3e41b4-2650-4840-9ccc-c46ea99e8b95"
authors = ["artur-gower"]
version = "1.0.0-DEV"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultipleScattering = "80a8ab25-5750-5d93-a6d7-4adc97cdd5fb"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Accessors = "^0.1.30"
BlockArrays = "^1.2, ^1.8, ^1.9"
LinearAlgebra = "^1"
MultipleScattering = "^0.1.22"
RecipesBase = "1.3.4"
StaticArrays = "^1.9, 1.9.15"
Statistics = "^1.6, ^1.10, 1.11.1"
SpecialFunctions = "^0.7, ^0.8, ^0.9, 0.10, 1, 2"
julia = "^1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "LinearAlgebra"]
